#!/bin/bash 

#
#    Created by Shaul Yermol 2018 
#    Copyright © 2018 Shaul Yemrol shaul.yermol@gmail.com. All rights reserved.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

FILE=$1
REVS=`git log ${FILE} | grep commit | cut -d ' ' -f 2`
REVS_ARRAY=()
SHOW_ARRAY=()
i=0
REVS_ARRAY=()
for rev in $REVS; do 
	SHOW=`git show --quiet --format="%Cgreen-- %cr %Cred[%cn] %Cgreen[%s]"  ${rev} ${FILE}`
       	printf "%d $SHOW\n" $i
	REVS_ARRAY[${i}]=${rev}
	SHOW_ARRAY[${i}]=${SHOW}
	i=$((i + 1))
done
while [ 1 ]
do
	echo
	echo
	echo Select the commits diff to show
	read -r -p 'Select first commit' FROM
	read -r -p 'Select second commit' TO 
	echo Showing diff from: ${FROM} ${REVS_ARRAY[$FROM]} ${SHOW_ARRAY[${FROM}]}
	echo Showing diff to: ${TO} ${REVS_ARRAY[$TO]} ${SHOW_ARRAY[${TO}]}
	git difftool -y ${REVS_ARRAY[$TO]} ${REVS_ARRAY[$FROM]} $FILE 
done
